# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

class InitialSchema < ActiveRecord::Migration
  def self.up
    create_table "account_features", :force => true do |t|
      t.column "name",  :string
      t.column "order", :integer
    end

    create_table "account_features_account_types", :id => false, :force => true do |t|
      t.column "account_feature_id", :integer
      t.column "account_type_id",    :integer
    end

    add_index "account_features_account_types", ["account_feature_id"], :name => "fk_account_features_account_types_account_feature_id"
    add_index "account_features_account_types", ["account_type_id"], :name => "fk_account_features_account_types_account_type_id"

    create_table "account_types", :force => true do |t|
      t.column "name",                   :string
      t.column "description",            :string
      t.column "current_price",          :float,   :default => 0.0
      t.column "order",                  :integer
      t.column "max_monthly_sales",      :integer
      t.column "max_products",           :integer
      t.column "private_storefront",     :boolean
      t.column "allow_paypal",           :boolean
      t.column "allow_merchant_account", :boolean
      t.column "commission",             :float,   :default => 0.0
      t.column "flat_fee",               :float,   :default => 0.0
    end

    create_table "accounts", :force => true do |t|
      t.column "account_type_id", :integer
      t.column "member_id",         :integer
      t.column "payment_type_id", :integer
      t.column "payment_info",    :string
      t.column "created_at",      :datetime
      t.column "updated_at",      :datetime
    end

    add_index "accounts", ["account_type_id"], :name => "fk_accounts_account_type_id"
    add_index "accounts", ["member_id"], :name => "fk_accounts_member_id"

    create_table "categories", :force => true do |t|
      t.column "name", :string
    end

    create_table "categories_products", :id => false, :force => true do |t|
      t.column "category_id", :integer, :default => 0, :null => false
      t.column "product_id",  :integer, :default => 0, :null => false
    end

    add_index "categories_products", ["category_id"], :name => "fk_categories_products_category_id"
    add_index "categories_products", ["product_id"], :name => "fk_categories_products_product_id"

    create_table "comatose_pages", :force => true do |t|
      t.column "parent_id",   :integer
      t.column "full_path",   :text
      t.column "title",       :string
      t.column "slug",        :string
      t.column "keywords",    :string
      t.column "body",        :text
      t.column "filter_type", :string,   :limit => 25, :default => "Textile"
      t.column "author",      :string
      t.column "position",    :integer,                :default => 0
      t.column "version",     :integer
      t.column "updated_on",  :datetime
      t.column "created_on",  :datetime
    end

    create_table "feedback", :force => true do |t|
      t.column "feedback",     :string
      t.column "line_item_id", :integer
      t.column "created_at",   :datetime
      t.column "comment",      :text
    end

    add_index "feedback", ["line_item_id"], :name => "fk_feedback_line_item_id"

    create_table "forum_groups", :force => true do |t|
      t.column "name",        :string
      t.column "description", :text
      t.column "created_at",  :datetime
      t.column "enabled",     :boolean
    end

    create_table "forum_posts", :force => true do |t|
      t.column "member_id",    :integer,  :default => 0,  :null => false
      t.column "subject",    :string,   :default => "", :null => false
      t.column "body",       :text
      t.column "root_id",    :integer
      t.column "parent_id",  :integer
      t.column "lft",        :integer
      t.column "rgt",        :integer
      t.column "depth",      :integer
      t.column "created_at", :datetime
      t.column "updated_at", :datetime
      t.column "forum_id",   :integer,  :default => 0,  :null => false
    end

    add_index "forum_posts", ["forum_id"], :name => "fk_forum_posts_forum_id"
    add_index "forum_posts", ["member_id"], :name => "fk_forum_posts_member_id"

    create_table "forums", :force => true do |t|
      t.column "name",           :string,   :limit => 50, :default => "", :null => false
      t.column "description",    :text
      t.column "created_at",     :datetime
      t.column "enabled",        :boolean
      t.column "forum_group_id", :integer
    end

    add_index "forums", ["forum_group_id"], :name => "fk_forums_forum_group_id"

    create_table "item_formats", :force => true do |t|
      t.column "name", :string
    end

    create_table "line_items", :force => true do |t|
      t.column "product_id",  :integer, :default => 0,   :null => false
      t.column "order_id",    :integer, :default => 0,   :null => false
      t.column "quantity",    :integer, :default => 0,   :null => false
      t.column "total_price", :float,   :default => 0.0, :null => false
    end

    add_index "line_items", ["product_id"], :name => "fk_line_item_products"
    add_index "line_items", ["order_id"], :name => "fk_line_item_orders"

    create_table "orders", :force => true do |t|
      t.column "name",                :string
      t.column "address_line_1",      :text
      t.column "email",               :string
      t.column "pay_type",            :string,   :limit => 10
      t.column "pay_info",            :string
      t.column "address_line_2",      :string
      t.column "city",                :string
      t.column "state",               :string,   :limit => 20
      t.column "zip",                 :string,   :limit => 10
      t.column "country",             :string,   :limit => 50
      t.column "ship_to",             :string
      t.column "ship_address_line_1", :string
      t.column "ship_address_line_2", :string
      t.column "ship_city",           :string
      t.column "ship_state",          :string,   :limit => 20
      t.column "ship_zip",            :string,   :limit => 10
      t.column "ship_country",        :string,   :limit => 50
      t.column "created_at",          :datetime
      t.column "member_id",             :integer
    end

    add_index "orders", ["member_id"], :name => "fk_orders_member_id"

    create_table "page_versions", :force => true do |t|
      t.column "page_id",     :integer
      t.column "version",     :integer
      t.column "parent_id",   :integer
      t.column "full_path",   :text
      t.column "title",       :string
      t.column "slug",        :string
      t.column "keywords",    :string
      t.column "body",        :text
      t.column "filter_type", :string,   :limit => 25, :default => "Textile"
      t.column "author",      :string
      t.column "position",    :integer,                :default => 0
      t.column "updated_on",  :datetime
      t.column "created_on",  :datetime
    end

    create_table "payment_types", :force => true do |t|
      t.column "name", :string
    end

    create_table "payment_types_sellers", :id => false, :force => true do |t|
      t.column "payment_type_id", :integer, :default => 0, :null => false
      t.column "seller_id",       :integer, :default => 0, :null => false
    end

    add_index "payment_types_sellers", ["payment_type_id"], :name => "fk_payment_types_sellers_payment_type_id"
    add_index "payment_types_sellers", ["seller_id"], :name => "fk_payment_types_sellers_seller_id"

    create_table "people", :force => true do |t|
      t.column "name",                      :string,   :limit => 40
      t.column "email",                     :string,   :limit => 100
      t.column "crypted_password",          :string,   :limit => 40
      t.column "salt",                      :string,   :limit => 40
      t.column "activation_code",           :string,   :limit => 40
      t.column "activated_at",              :datetime
      t.column "created_at",                :datetime
      t.column "updated_at",                :datetime
      t.column "remember_token",            :string
      t.column "remember_token_expires_at", :datetime
    end

    create_table "points", :force => true do |t|
      t.column "member_id",      :integer
      t.column "rating_id",    :integer
      t.column "feedback",     :text
      t.column "created_at",   :datetime
      t.column "created_by",   :integer
      t.column "line_item_id", :integer
    end

    add_index "points", ["member_id"], :name => "fk_points_member_id"
    add_index "points", ["line_item_id"], :name => "fk_points_line_item_id"
    add_index "points", ["created_by"], :name => "fk_created_by_points"

    create_table "product_images", :force => true do |t|
      t.column "data",       :binary
      t.column "product_id", :integer
    end

    add_index "product_images", ["product_id"], :name => "fk_product_images_product_id"

    create_table "product_reviews", :force => true do |t|
      t.column "isbn",       :string
      t.column "name",       :string
      t.column "author",     :string
      t.column "publisher",  :string
      t.column "content",    :text
      t.column "member_id",    :integer
      t.column "created_at", :datetime
      t.column "rating_id",  :integer
    end

    add_index "product_reviews", ["member_id"], :name => "fk_product_reviews_member_id"
    add_index "product_reviews", ["rating_id"], :name => "fk_product_reviews_rating_id"

    create_table "products", :force => true do |t|
      t.column "title",          :string
      t.column "description",    :text
      t.column "price",          :float,                 :default => 0.0
      t.column "condition",      :string
      t.column "created_at",     :datetime
      t.column "updated_at",     :datetime
      t.column "publish_at",     :datetime
      t.column "published",      :boolean,               :default => true
      t.column "discount_desc",  :string
      t.column "discount_price", :float
      t.column "quantity_avail", :integer,               :default => 1,    :null => false
      t.column "isbn",           :string
      t.column "internal_id",    :string
      t.column "status_id",      :integer,  :limit => 2
      t.column "seller_id",      :integer
      t.column "item_format_id", :integer
      t.column "publisher_name", :string
    end

    add_index "products", ["seller_id"], :name => "fk_products_seller_id"
    add_index "products", ["item_format_id"], :name => "fk_products_item_format_id"

    create_table "products_publishers", :id => false, :force => true do |t|
      t.column "product_id",   :integer, :default => 0, :null => false
      t.column "publisher_id", :integer, :default => 0, :null => false
    end

    add_index "products_publishers", ["product_id"], :name => "fk_products_publishers_product_id"
    add_index "products_publishers", ["publisher_id"], :name => "fk_products_publishers_publisher_id"

    create_table "profiles", :force => true do |t|
      t.column "name",        :string
      t.column "description", :text
      t.column "active",      :boolean
    end

    create_table "publishers", :force => true do |t|
      t.column "name", :string
      t.column "url",  :string
    end

    create_table "ratings", :force => true do |t|
      t.column "name",  :string
      t.column "score", :integer
    end

    create_table "sellers", :force => true do |t|
      t.column "name",           :string
      t.column "address_line_1", :string
      t.column "address_line_2", :string
      t.column "city",           :string
      t.column "state",          :string,  :limit => 20
      t.column "zip",            :string,  :limit => 10
      t.column "country",        :string,  :limit => 50
      t.column "email",          :string,  :limit => 80, :default => "", :null => false
      t.column "member_id",      :integer
      t.column "phone",          :string,  :limit => 30
      t.column "pay_pal_id",     :string
      t.column "merchant_id",    :string
      t.column "image",          :binary
    end

    create_table "sessions", :force => true do |t|
      t.column "session_id", :string
      t.column "data",       :text
      t.column "updated_at", :datetime
    end

    add_index "sessions", ["session_id"], :name => "sessions_session_id_index"

    create_table "statuses", :force => true do |t|
      t.column "name", :string
    end

  end

  def self.down
    drop_table :products
    drop_table :account_features
    drop_table :account_features_account_types
    drop_table :account_types
    drop_table :accounts
    drop_table :categories
    drop_table :categories_products
    drop_table :comatose_pages
    drop_table :feedback
    drop_table :forum_groups
    drop_table :forum_posts
    drop_table :forums
    drop_table :item_formats
    drop_table :item_formats_products
    drop_table :line_items
    drop_table :orders
    drop_table :page_versions
    drop_table :payment_types
    drop_table :payment_types_sellers
    drop_table :people
    drop_table :points
    drop_table :product_images
    drop_table :product_reviews
    drop_table :products
    drop_table :products_publishers
    drop_table :profiles
    drop_table :publishers
    drop_table :ratings
    drop_table :roles
    drop_table :roles_users
    drop_table :sellers
    drop_table :sellers_users
    drop_table :sessions
    drop_table :statuses
    drop_table :users
  end
end